server:
  port: 8105
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #    JDBC : SGDB :// HOST : PORT / DB
    url: jdbc:postgresql://localhost:5432/docseeker
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true
